package main

import (
	"os"

	_ "your_module/api" // docs is generated by Swag CLI, you have to import it.
	"your_module/internal/app/api"
	"your_module/internal/pkg/env"

	"your_module/internal/pkg/logger"
)

// @title           Swagger foo API
// @version         1.0
// @description     This is a sample server Petstore server.
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      petstore.swagger.io
// @BasePath  /v2
func main() {
	e := env.Prepare()
	l := logger.Prepare(os.Stdout, e.LogLevel())

	if err := api.Start(l, e); err != nil {
		l.FatalErr(err)
	}
}
