package main

import (
	"os"

	_ "your_module/api" // docs is generated by Swag CLI, you have to import it.
	"your_module/internal/app/api"
	"your_module/internal/pkg/env"

	"your_module/internal/pkg/logger"
)

// @title     Swagger baaa API
// @host      petstore.swagger.io
// @BasePath  /api
func main() {
	e := env.Prepare()
	l := logger.Prepare(os.Stdout, e.LogLevel())

	if err := api.Start(l, e); err != nil {
		l.FatalErr(err)
	}
}
