basePath: /api
definitions:
  routes.Error:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  routes.User:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
    required:
    - name
    type: object
host: petstore.swagger.io
info:
  contact: {}
  title: Swagger baaa API
paths:
  /accounts:
    get:
      consumes:
      - application/json
      description: get accounts
      parameters:
      - description: name search by q
        format: email
        in: query
        name: q
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/routes.User'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/routes.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/routes.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/routes.Error'
      summary: List accounts
      tags:
      - accounts
swagger: "2.0"
