name: Swagger
on:
  pull_request:
    branches:
      - main
        #    paths:
        #      - '**.go'
jobs:
  generate:
    name: Foo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: commit & push
        run: |
          git add .
          #if ! git diff --exit-code --quiet
          #then
          #  git config user.name github-actions
          #  git config user.email github-actions@github.com
          #fi
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git commit -m "[GitHub Actions] Generate swagger"
          git push github HEAD:${GITHUB_REF}
