name: Swagger
on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - '**.go'

jobs:
  generate:
    name: Generate
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref }}
      - name: Try
        run: |
          git branch
      - name: Swag init
        run: |
          docker build -t swag build/package
          docker run -w /home/app -v `pwd`:/home/app swag swag i -o api --ot go,yaml -g cmd/rest-json-api/main.go
      - name: Commit and push
        run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"

          git add -N .
          git diff --exit-code --quiet || git commit -a -m "[GitHub Actions] Generate swagger"
          git push
