name: Swagger
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'api/**'
        #    paths:
        #      - '**.go'
        #        paths:
        #- 'sub-project/**'
        #- '!sub-project/docs/**'
jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref }}
      - name: Swag init
        run: |
          docker build -t swag build/package
          docker run -w /home/app -v `pwd`:/home/app swag swag i -o api --ot go,yaml -g cmd/rest-json-api/main.go
      - name: Commit and push
        run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"


          git add -N .
          git diff --exit-code --quiet || git commit -a -m "[GitHub Actions] Generate swagger"
          git push
          # git push origin HEAD:${GITHUB_REF}

          # git add .
          # #if ! git diff --exit-code --quiet
          # #then
          # #  git config user.name github-actions
          # #  git config user.email github-actions@github.com
          # #fi
          # git config --local user.email "$(git log --format='%ae' HEAD^!)"
          # git config --local user.name "$(git log --format='%an' HEAD^!)"

          # git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"

          # git diff --exit-code || git commit -m "[GitHub Actions] Generate swagger"
          # 
          # git push github HEAD:${GITHUB_REF}
