name: Swagger
on:
  pull_request:
    branches:
      - main
        #    paths:
        #      - '**.go'
jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: commit & push
        run: |
          pwd
          ls
          docker-compose run api swag i -o api --ot go,yaml -g cmd/rest-json-api/main.go
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git commit --allow-empty -m 'emp'


          git add .
          git diff --exit-code || git commit -m "[GitHub Actions] Generate swagger"
          git push origin HEAD:${GITHUB_REF}

          # git add .
          # #if ! git diff --exit-code --quiet
          # #then
          # #  git config user.name github-actions
          # #  git config user.email github-actions@github.com
          # #fi
          # git config --local user.email "$(git log --format='%ae' HEAD^!)"
          # git config --local user.name "$(git log --format='%an' HEAD^!)"

          # git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"

          # git diff --exit-code || git commit -m "[GitHub Actions] Generate swagger"
          # 
          # git push github HEAD:${GITHUB_REF}
